    @extends('fe.master')
    @section('hero')
        @include('fe.hero')
    @endsection
    @section('appointment')
        @include('fe.appointment')
    @endsection
    @section('feature')
        @include('fe.feature')
    @endsection
    @section('team')
        @include('fe.team')
    @endsection
    @section('testimonial')
        @include('fe.testimonial')
    @endsection
    @section('pricing')
        @include('fe.pricing')
    @endsection
    @section('map')
        @include('fe.map')
    @endsection